version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: flake8-comprehensions
    versions:
    - 3.3.1
  - dependency-name: rope
    versions:
    - 0.18.0
